베이스볼 코드 리뷰 부탁드립니다.
selab-hs/selab-baseball-game pull request #11
Opened 2022-07-21 16:04 UTC by sonrose

### 구현 내용

1. **Input Class**
   사용자에게 값을 입력 받는 클래스

   - **input()**
     입력 받은 문자열을 하나씩 분리해 배열 number에 넣는다.
     값에 중복이 있는지, 3글자가 맞는지 검사한 후 이를 만족하지 못하면 재입력 받는다.
     배열에 있는 값을 정수로 변환한 뒤 리스트에 넣고 반환한다.
   
   - **clear()**
     리스트를 초기화한다.

   - **inputData()**
     값을 입력 받고 한 글자씩 분리한다.
   
   - **checkForLength(String[] nums)**
     문자열의 길이가 3인지 검사한다. 만약 3이 아닐 경우 true를 반환한다.

   - **checkForDuplicates(String[] nums)**
     중복값이 있는지 검사한다. 만약 중복값이 있을 경우 true를 반환한다. (배열의 총 개수와 중복값을 걸러낸 개수 비교)

---

2. **RandomNumber Class**
    랜덤한 정수를 생성하는 클래스
    
    - **createRandomNumber()**
      중복값이 없도록 Set으로 값을 저장한다. 리스트에 3개가 들어갈 때까지 반복해서 랜덤값을 생성하고 넣는다.

---

3. **Comparison Class**
    사용자가 입력한 값과 랜덤 생성한 값을 비교하는 클래스

    - **compareNumber(ArrayList<Integer> input, ArrayList<Integer> randomNumber)**
      만약 입력 값과 랜덤값 중 순서 상관없이 겹치는 값이 있다면 ball을 하나 늘린다.
      순서도 같이 겹치는 값이 있다면 strike를 하나 늘린다.

---

4. **Output Class**
    결과를 출력하는 클래스

    - **output(int strike, int ball)**
      strike와 ball 값을 받아와, 만약 strike가 3이면 답을 맞힌 것이므로 BASEBALL WIN~!을 출력한다.
      정답을 맞히지 못했다면 ball, strike 여부를 알려준다.

---

### 궁금한 점

main에 있는 while문... 실행문 안에 아무것도 안 들어가도 되나요...

2022-07-22 01:39 UTC, DongGeon0908 requested changes
읽기 쉬운, 그런 코드를 짜보시죵!

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    private static final Set<Integer> randomNumbersSet = new HashSet<>();
해당 변수를 메모리에서 관리해야 하나요?
왜 static을 쓰신거죠?

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    public ArrayList<Integer> createRandomNumber() {
```suggestion
    public List<Integer> createRandomNumber() {
```

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +public class Comparison {
야구라는 도메인에서 필요한 객체는 무엇일까요?

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +    int strike;
접근제한자는?

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +        strike = 0;
???????초기화를 의미하는 걸까요?

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +            }
if else 쓰지 않고 한번 도전해볼까요?

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +        output.output(strike, ball);
여기서 출력을 실행할 이유가 있을까요?

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Main.java
>          System.out.println("Play Baseball Game");
이것도 output으로 빼도 좋을듯

2022-07-22 01:39 UTC, DongGeon0908 commented on src/main/java/Input.java
> +    }
메서드가 길어진다면, 너무 많은 기능을 하나에서 진행한다고 생각하시면 됩니다

2022-07-30 08:48 UTC, DongGeon0908 requested changes
메서드 분리 작업에서 노력하신 것 같네요!
고생하셨어요

이제는 객체와 객체가 서로 메세지를 던지며 상호작용하도록 수정하시죠!!

2022-07-30 08:48 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    private static final Set<Integer> randomNumbersSet = new HashSet<>();
Set이라는 명칭을 사용하지 않습니다!

2022-07-30 08:48 UTC, DongGeon0908 commented on src/main/java/Main.java
> +        }
???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

2022-07-30 08:48 UTC, DongGeon0908 commented on README.md
>  wrjs@naver.com
Readme 작성 좋네요

2022-07-30 08:48 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    private Set<Integer> randomNumber = new HashSet<>();
클래스를 생성할 때 만들어주는 건 어떨까요?

2022-07-30 08:48 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +        return randomNumbers;
```suggestion
        return new ArrayList<>(randomNumber);
```

2022-07-31 08:19 UTC, DongGeon0908 reviewed
굳굳

2022-07-31 08:23 UTC, DongGeon0908 requested changes
객체가 다른 객체에게 메세지를 던진다는 의미가 무엇일까요??
어려운 개념이긴 하지만, 한번 더 고민해서 수정해보세요!!
(거의 끝나가요!)

2022-07-31 08:23 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    }
접근제한자를 default로 한 이유는 무엇일까요?

2022-07-31 08:23 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +        System.out.println(randomNumber);
출력하는 부분을 따로 빼는 건 어떨까요?

2022-07-31 08:23 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +    private int strike;
생성자로 초기화할 수는 없나용?

2022-07-31 08:23 UTC, DongGeon0908 commented on src/main/java/Comparison.java
> +    }
2개가 아에 같은 로직으로 구성되어 있는 것 같아요!
아에 strike인지, ball인지 데이터를 넘겨주면 바로 알려줄 수 있는 별도의 클래스를 만드는 건 어떨까요>

2022-07-31 08:23 UTC, DongGeon0908 commented on src/main/java/Input.java
> +        List<Integer> numbers = number.stream().map(s -> Integer.parseInt(s)).collect(Collectors.toList());
이거 하나의 문장으로 바꿀 수 있을 것 같아여

2022-08-02 13:01 UTC, DongGeon0908 requested changes
추상클래스를 쓰신건 좋은데, 조금 더 광범위하게 쓰일 수 있도록 네이밍을 정해주세요!
각 클래스마다 역할과 책임을 다할 수 있도록 분리했으면 좋겠습니다
그리고 불변객체에 대해 공부해보세요

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +    private int ball;
strike class가 ball도 알고 있어야 할까요?

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +    Strike() {
접근제한자~

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +    private int strike;
final 사용하지 않은 이유가 무엇일까용?
불변객체에 대해 이번에 학습해보시길 추천드립니다

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Main.java
> +            result = new int[]{totalBall, totalStrike};
이부분이 이해가 되지 않네요
이미 위에서 선언했는데, 또 생성한 이유가 있나요?

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Input.java
> +    public List<Integer> arrToList(String[] str) {
자료구조 명칭은 메서드 네이밍으로 정하지 않습니다

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +    public abstract int checkBallOrStrike(List<Integer> randomNumber, List<Integer> userNumber);
해당 추상메서드가 어색한 것 같아요
차라리 check라고 가져가는게 어떨까요?

2022-08-02 13:01 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    Ball() {
접근제한자는?

2022-08-03 01:35 UTC, DongGeon0908 requested changes
고생하셨습니다!!
거의 끝나가네요
몇가지 질문 및 개선사항에 대해 피드백 드렸습니다

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    public int check(List<Integer> randomNumber, List<Integer> userNumber) {
보통 유효성 검사 네이밍은 check 또는 validate를 사용합니다

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +        return ball;
stream으로 한문장안에 끝낼 수 있을 것 같아용

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +public abstract class Baseball {
인터페이스로 만드는 건 어떤까요?

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Input.java
> +        if (numbers.size() != numbers.stream().distinct().count()) {
```suggestion
int count =  numbers.stream().distinct().count()

        if (numbers.size() != count) {
```

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Input.java
> +        if (numbers.size() != numbers.stream().distinct().count()) {
보통은 if문 안에 조건이 긍정이 되도록 구성하는게 좋아요
읽기 편하거든요

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Main.java
> +        int totalBall;
초기화하지 않은 값에는 어떤게 들어달까요?

2022-08-03 01:35 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +public class Strike extends Baseball {
Baseball이라는 계층을 주어서 추상화한 이유가 궁금합니다

2022-08-03 01:42 UTC, DongGeon0908 commented
한단계 점프업을 위해 배열 -> 리스트로 전부 바꾸시죠!!

2022-08-05 10:29 UTC, sonrose commented on src/main/java/Strike.java
> +public class Strike extends Baseball {
안에 있는 메서드가 중복되어서, 이걸 아예 하나의 baseball 객체(클래스)로 만든 다음에 ball과 strike로 나누면 더 깔끔할 것 같아서 추상 클래스로 만들었습니다.

2022-08-06 13:21 UTC, DongGeon0908 reviewed
조금 더 읽기 쉬운 코드로 수정하시고, 이번 과제는 끝내도 될 것 같습니다

2022-08-06 13:21 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +        return (int) IntStream.range(0, 3).filter(n -> randomNumber.get(n).equals(userNumber.get(n))).count();
조금 더 깔끔하게 수정할 수 있을 것 같네요

2022-08-06 13:21 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +            randomNumber.add((int) (Math.random() * 9 + 1));
정말 랜덤한지 어떻게 증명할 수 있을까요?

2022-08-06 13:21 UTC, DongGeon0908 commented on src/main/java/Main.java
> +        int totalBall = 0;
여기에 꼭 필요한 값일까요?

2022-08-06 13:21 UTC, DongGeon0908 commented on src/main/java/Input.java
> +        List<Integer> numbers = Pattern.compile("").splitAsStream(str).map(Integer::parseInt).collect(Collectors.toList());
조금 더 깔끔하게?
코드를 읽기 쉽게 보여주시는게 좋을 것 같네요

2022-08-06 13:21 UTC, DongGeon0908 commented on src/main/java/Input.java
> +        if(numbers.size() > 3 || numbers.size() < 3 || numbers.contains(0)) {
해당 부분에 대해 조금 더 나눠 볼 수 있을까요?

2022-08-06 13:21 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    }
깔끔하게 수정하기!

2022-08-11 17:29 UTC, sonrose commented on src/main/java/Input.java
> +        List<Integer> numbers = Pattern.compile("").splitAsStream(str).map(Integer::parseInt).collect(Collectors.toList());
객체지향 생활체조 원칙 중 <한 줄에 점을 하나만 찍는다.> 이걸 말씀하시는 것 같아 점을 기준으로 나눴어요.
이거 말고는... 읽기 쉽게 한다는 게 어떻게 하는 것인지 잘 모르겠어요.

2022-08-11 17:56 UTC, sonrose commented on src/main/java/RandomNumber.java
> +            randomNumber.add((int) (Math.random() * 9 + 1));
Math.random이 정말 랜덤한지 찾아보니, 유사 난수를 생성한다고 하더군요. (시드값도 설정 불가)
즉, 난수를 계속 생성하다 보면 어떠한 패턴이 나타난다고 합니다.
따라서 Math.random이 아닌 java.util의 Random을 사용해 시드값을 System.currentTimeMillis()로 설정하였습니다.

그런데 제 생각에는 java.util의 Random도 Math.random보다 좀 더 나을뿐, 결국 유사 난수를 생성하는 건 변함 없는 것 같은데, 제 생각이 맞나요?

2022-08-12 03:29 UTC, DongGeon0908 reviewed
고생하셨습니다
랜덤 넘버에 대한 유효성 로직만 추가하면 될 것 같아요!!
그 부분만 추가하시고, 다음 단계로 넘어가시죠
pr은 닫을게요~~

2022-08-12 03:29 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    }
해당 값이 정말 랜덤한지 validate해주는 로직이 있으면 좋겠네요

2022-08-12 03:29 UTC, merged