베이스볼 구현
selab-hs/selab-baseball-game pull request #12
Opened 2022-07-30 18:15 UTC by twoosky

객체지향 생활체초 매일 아침 일어나자마자 하고 있습니다. ^^
어렵네요 맞을 준비 완료.
코드 리뷰 감사합니다 극락
요구사항 분석 및 리드미 작성은 이따 일어나서 하겠습니다

2022-07-31 08:24 UTC, DongGeon0908 commented
README를 작성해주세요

2022-07-31 08:29 UTC, DongGeon0908 requested changes
잘했어요!!
메서드를 잘 쪼갰습니다!!
그러면 다음 pr때는 class를 조금 더 분리시키시죵!!

2022-07-31 08:29 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +        System.out.println("랜덤값: "+ Arrays.toString(randNum));
output 내용이 여기 있는게 맞을까요?

2022-07-31 08:29 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +    }
Ball.class, Strike.class를 만든는 건ㄷ 어떨끼요??

2022-07-31 08:29 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +public class Baseball {
모든 서비스 로직이 해당 클래스에 몰빵되어 있네요!!
조금 더 객체를 나눠보는 건 어떨까요??

해당 과제의 요구사항을 다시 분석해서 나눠보시죠!!
(물론, 지금처럼 구현해도 문제는 없지만, 우리는 공부하는 거니까!)

2022-07-31 08:29 UTC, DongGeon0908 commented on src/main/java/OutputUtil.java
> +    }
flag 값만 주면 알아서 우리가 원하는 출력 메세지를 줄수는 없을까요??
이것도 결국에는 if-else인 것 같은데..

2022-08-02 17:59 UTC, twoosky commented on src/main/java/Baseball.java
> +        System.out.println("랜덤값: "+ Arrays.toString(randNum));
테스트용이라 삭제하겠습니다!

2022-08-02 17:59 UTC, twoosky commented on src/main/java/Baseball.java
> +    }
넵 클래스 분리하겠습니다. 코드리뷰 감사합니다 극락 :)

2022-08-02 18:00 UTC, twoosky commented on src/main/java/Baseball.java
> +public class Baseball {
넵 !! 요구사항 분석 중요하군요

2022-08-02 18:04 UTC, twoosky commented on src/main/java/OutputUtil.java
> +    }
흠 ,, 이 부분은 아직 좋은 방법이 생각나질 않네요 
등호(=) 연산의 조건이라면 if문을 피할 수 있겠지만,
부등호(>, <) 연산의 조건인 경우 if문을 피할 좋은 방법이 떠오르지 않습니다 ,,
좋은 방법이 있을까요?

2022-08-03 01:42 UTC, DongGeon0908 requested changes
고생하셨습니다!
한단계 점프업을 위해 배열 -> 리스트로 전부 바꾸시죠!!

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    private int ball;
final하게 가도 좋지 않을까요?
불변객체란 무엇일까요?

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    }
if문 안에 있는 조건들이 너무 무거워서 읽기 어렵네요 ㅜㅜㅜ
조금더 가독성있게 작성해보는 건 어떨까요??

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +    private String[] input;
final하게 가져가도 좋을 것 같아요

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +        Ball ballInstance = new Ball();
변수명을 strike, ball이라고 가져가는 않될까요??

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +    private int strike;
final하게 가져가는게 좋을 것 같아요

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/RandNum.java
> +        return String.valueOf(random.nextInt(999)).split("");
해당 값에 대한 검증은 어디서 할까요?

2022-08-03 01:42 UTC, DongGeon0908 commented on src/main/java/OutputUtil.java
> +    }
디자인 패턴을 이용해보는 건 어떨까요??
아니면 if문 안에 있는 것들을 전부 메서드로 뽑은 다음에, 특정 flag를 통해 명령을 주는 방식도 좋을 것 같아요

2022-08-03 01:43 UTC, DongGeon0908 commented
README가 보이지 않는데, 다음 리뷰 요청때는 꼭 리드미 작성부탁드립니다

2022-08-03 16:58 UTC, twoosky commented on src/main/java/Ball.java
> +    private int ball;
현재 로직 상 ball 값은 변경가능해야 하는데 final 붙이면 안되지 않나요??

2022-08-03 16:58 UTC, twoosky commented on src/main/java/Ball.java
> +    }
리스트 사용해 좀 더 간결히 작성해보겠습니다 !

2022-08-03 17:00 UTC, twoosky commented on src/main/java/Baseball.java
> +    private String[] input;
현재 사용자가 랜덤값을 맞추지 못한 경우 계속해서 입력값을 받는 로직으로 구성되어 있는데,
final을 사용하면 입력값이 변경 불가능하지 않나요??

2022-08-03 17:02 UTC, twoosky commented on src/main/java/RandNum.java
> +        return String.valueOf(random.nextInt(999)).split("");
검증이 어떤 검증인가요 ??!!
랜덤값을 사용자 입력과 비교하여 게임을 진행하는 로직은 Baseball class의 run()메소드에 있습니다.

2022-08-03 17:03 UTC, twoosky commented on src/main/java/OutputUtil.java
> +    }
오홍 .. 도전해보겠습니다 감사합니다 극락!

2022-08-06 13:17 UTC, DongGeon0908 requested changes
고생하셨습니다!!
리뷰드린 내용에 대해 수정 부탁드립니다!

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    private int ball;
해당 객체가 해야 하는 역할이 무엇일까요?

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    }
삼항 연산자는 사용하지 마세용

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +                randNum.contains(input.get(idx))) {
이것이 무엇을 하는지 모르겠습니다!!
조금 더 깔끔하게, 다른 사람이 코드를 읽는데 쉽도록 구현 부탁드립니다!

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +        }
ball이라는 변수에서 발생할 수 있는 문제가 무엇이 있을까요?
저 변수는 언제까지 관리가 되는 값일까요?

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +    }
조금 더 깔끔하게 할 수 있을 것 같아요

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/OutputUtil.java
> +        }
Enum으로 관리하는게 어떨까요?

2022-08-06 13:17 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +            System.out.println("idx: " + i);
println을 여기서 하는게 맞을까요?

2022-11-02 14:09 UTC, DongGeon0908 commented
PR을 종료합니다

2022-11-02 14:09 UTC, merged