베이스볼 1차 구현
selab-hs/selab-baseball-game pull request #13
Opened 2022-08-03 08:43 UTC by xx10222

2022-08-03 09:05 UTC, DongGeon0908 requested changes
고생하셨습니다

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/StrikeUtil.java
> +    private int strike;
final하게 가는게 좋을 것 같네요!
시간되실 때 불변객체에 대해 공부해보시길

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/BallUtil.java
> +    private int ball;
final하게 가는게 좋을 것 같네요!
시간되실 때 불변객체에 대해 공부해보시길

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/BallUtil.java
> +    BallUtil(int ball) {
접근제한자는?

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/BallUtil.java
> +        return !randomNumber[index].equals(input[index]) && Arrays.stream(randomNumber).anyMatch(r -> r.equals(input[index]));
해당 메서드가 어떤 일을 하는지 모르겠어요
가독성 있게 수정 부탁드립니다

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/StrikeUtil.java
> +public class StrikeUtil {
class명에 Util이 들어가는 이유를 설명해주세요

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/CheckArrayDupplicate.java
> +    CheckArrayDupplicate() {
접근제한자는?

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/CheckArrayDupplicate.java
> +    }
유효성 검사를 랜덤 숫자 만들어주는 곳에서 메서드로 활용했어도 충분할 것 같습니다

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +        } while (!checkArrayDupplicate.checkDuplicate(result) || result.length != 3);
do-while을 쓰지 않고 구현해보세요

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +        String[] result;
한단계 점프업을 위해 배열을 쓰지 않고, 리스트로 구현해보세요

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/OutputUtil.java
> +        }
if는 한번만,
그러면 어떤식으로 코드를 구현해야 될까요?

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +        String[] randomNumber = RandomNumber.generateRandomNumber();
배열 -> 리스트로!

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +        BallUtil ballUtil = new BallUtil(0);
두개가 하는 역할이 무엇인가요?

2022-08-03 09:05 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +            }
이친구는 따로 빼서 플래그 값만 던져주는게 제일 이상적일 듯 합니다

2022-08-07 04:43 UTC, xx10222 commented on src/main/java/StrikeUtil.java
> +public class StrikeUtil {
Strike와 관련된 작업을 하는 클래스여서 Util을 붙였는데 다시 보니까 없어도 될 것 같슴둥!

2022-08-12 12:14 UTC, xx10222 commented on src/main/java/Baseball.java
> +        BallUtil ballUtil = new BallUtil(0);
strike랑 ball 클래스를 초기화해서 생성하는 역할을 합니당..

2022-08-14 05:27 UTC, DongGeon0908 reviewed
접근제한자, 읽기 쉬운 코드 등을 고려해서 마지막으로 수정 한번 더 하시졍

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +        return !randomNumber.get(index).equals(input.get(index)) && input.contains(randomNumber.get(index));
메서드를 분리하시죠!!
읽기 어려워요 ㅜ

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    private int ball;
final하게 가는게 좋을 것 같아요

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +        Ball ball = new Ball(0);
생성할때부터 초기화하는건 어떨까요?
생성자로 초기값을 0으로 강제할 수 잇을 것 같네요

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/Baseball.java
> +        List<String> input;
선언하면서부터 초기화하는게 좋아요

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    public static List<String> generateRandomNumber() {
static을 사용한 이유가 있을까요?

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +        CheckArrayDupplicate checkArrayDupplicate = new CheckArrayDupplicate();
Random한 값인지, 그리고 중복되지 않았는지는 RandomNumber의 책임 아닐까요?

2022-08-14 05:27 UTC, DongGeon0908 commented on src/main/java/Strike.java
> +    private int strike;
접근제한자

2022-08-19 09:35 UTC, xx10222 commented on src/main/java/RandomNumber.java
> +        CheckArrayDupplicate checkArrayDupplicate = new CheckArrayDupplicate();
랜덤한 값인지는 해당 클래스에서 검사하고 있고, 중복 검사는 사용자 입력 값에 중복된 값이 있는지 판단할 떄도 쓰여서 checkArrayDuplicate라는 클래스로 따로 만들어서 사용하고 있습니다!

2022-08-19 09:39 UTC, xx10222 commented on src/main/java/RandomNumber.java
> +    public static List<String> generateRandomNumber() {
다른 클래스에서 사용할 떄 RandomNumber 인스턴스를 만들지 않고 바로 메서드만 호출하려고 static을 사용했는데 지금 보니 굳이 static을 사용할 필요가 없을 것 같습니당!

2022-08-19 10:59 UTC, DongGeon0908 commented
몇가지 질문을 드릴게요
1. 생성자가 하는 일은 무엇일까요?
2. 메서드가 하는 일은 무엇일까요?
3. 롬복이 언제 코드를 만들어줄까요? (롬복의 동작과정)

2022-08-21 11:45 UTC, xx10222 commented
> 몇가지 질문을 드릴게요
> 
> 1. 생성자가 하는 일은 무엇일까요?
> 2. 메서드가 하는 일은 무엇일까요?
> 3. 롬복이 언제 코드를 만들어줄까요? (롬복의 동작과정)

1) 외부에서 클래스를 사용하기 위해 생성하는 인스턴스를 초기화하는 역할을 합니다!
2) 어떤 문제를 처리하기 위한 코드를 필요에 따라 호출하여 동작하는 기능입니다!
3) 컴파일 시점에 바이트 코드를 변환하여 원하는 부분을 주입해줍니다!

2022-09-03 04:51 UTC, merged