Sangho/working
selab-hs/selab-baseball-game pull request #14
Opened 2022-10-07 18:17 UTC by LSH-3016

시간이 너무 오래걸려버린점 죄송합니다
패키지와 역할별로 최대한 클래스를 나누어 보았습니다만 아직 미숙한것 같습니다
코멘트를 주신다면 이에 맞게 수정해보겠습니다

2022-10-08 12:57 UTC, DongGeon0908 requested changes
고생하셨습니다.
1. 네이밍 전략 다시 한번 더 학습 (자료구조를 네이밍으로 쓰지 않습니다.)
2. 객체지향 생활체조 원칙을 지키기
3. 누구나 봤을 때 이해하기 쉬운 코드로 작성하기

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/model/Numbers.java
> +    public static final int MAX_NUMBER = 999;
단순하게 메서드에 숫자가 있어서, 상수로 빼서 처리하는 건 별로 좋지 않아요!
그 숫자가 명확하게 의미하는 바가 있는 확인하고 상수처리해주세요

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/domain/RandomNumberService.java
> +    Random random = new Random();
접근제한자는요?

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/domain/RandomNumberService.java
> +            if (!DuplicateCheck.checkingDuplicate(randomNumber.getList(), randomNumber.getSize())) {
이런 구조라면, List만 던져도 되는거 아닌가요? check 로직에서 리스트 사이즈로 비교하면 될 것 같은데

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/domain/UserNumberService.java
> +    private void DigitizingNumber(int num) {
```suggestion
    private void digitizingNumber(int num) {
```

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/domain/UserNumberService.java
> +        } while (!completionCheck);
do-while을 사용하지 않고 구현 부탁드립니다!

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/domain/Strike.java
> +            }
if문을 별도의 메서드로 빼는 건 어려울까요?

2022-10-08 12:57 UTC, DongGeon0908 commented on src/main/java/controller/BaseballGame.java
> +        }
객체지향 생활체조원칙을 지켜주세요!!

2022-11-02 13:04 UTC, LSH-3016 commented
중첩문의 최소화와 로직을 최대한 수정해보았습니다
수정을 하다보니 질문이 생겼습니다
질문 : 현재 controller-BaseballGame 클래스 안에 객체들을 public static final로 생성해두었습니다. 그런데 현재 프로젝트를 진행하다보니 각자의 클래스안에 객체들을 같은 방법으로 각각 생성해두어도 괜찮을듯 싶습니다. 어떤 방법이 맞거나 나은방법인지 궁금합니다.

2022-11-02 14:09 UTC, DongGeon0908 reviewed
해당 작업은 여기서 끝내시죠!
TODO 바로 진행하시면 될 것 같습니다

2022-11-02 14:09 UTC, merged