BaseballGame 리뷰 요청드립니다!! - 19 박창주
selab-hs/selab-baseball-game pull request #16
Opened 2023-06-29 11:38 UTC by ds4pae

저번에 진행했던 `StringCalculator`에서 `ArrayList`로 구현한 경험이 있어서
`inputValue` 와 `randomValue` 를 `ArrayList`로 하면 `hasDuplicateDigit()`코드 부분이 깔끔해지지 않을까...고민중입니다!

2023-06-30 03:39 UTC, DongGeon0908 requested changes
GOGO

2023-06-30 03:39 UTC, DongGeon0908 commented on src/main/java/RandomValue.java
> +    private static String randomValue = "";
전역변수로 관리하지 않고 사용할 수 있는 방법이 있을 것 같네요

2023-06-30 03:39 UTC, DongGeon0908 commented on src/main/java/PlayBaseballGame.java
> +    }
input class 처럼 output class를 분리하는게 좋을 듯 합니다.

2023-06-30 03:39 UTC, DongGeon0908 commented on src/main/java/RandomValue.java
> +    }
변수로 할당에서 메모리에 저장해두고 쓰는게 아니라, 매 요청마다 새로운 값을 서빙만 하는 건 어떨지

2023-06-30 03:39 UTC, DongGeon0908 commented on src/main/java/PlayBaseballGame.java
> +public class PlayBaseballGame {
Ball이라는 개념을 조금 더 추상화해보는 건 어떨까요?

2023-06-30 03:39 UTC, DongGeon0908 commented on src/main/java/PlayBaseballGame.java
> +public class PlayBaseballGame {
Strike와 Ball이라는 규격이 있으니까, 각각의 성질에 맞추어 역할과 책임을 나눠주는 건?

2023-06-30 11:30 UTC, ds4pae commented on src/main/java/RandomValue.java
> +    private static String randomValue = "";
`randomValue`를 제거했습니다. 아래에서 추가로 설명할게요!

2023-06-30 11:32 UTC, ds4pae commented on src/main/java/PlayBaseballGame.java
> +    }
`PrintResult`클래스 생성해서 분리했습니다~!
- 작업 도중에 `checkAnswer`도 합쳐서 `PrintResult `클래스에서 결과 출력을 모두 담당하도록 할당하는 것이
가독성이 좋을 것 같아 수정했습니다!

2023-06-30 11:33 UTC, ds4pae commented on src/main/java/RandomValue.java
> +    }
변수 `randomValue`를 삭제하고 `PlayBaseball`클래스에서 `generateRandomValue`를 호출해 사용했습니다!

2023-07-01 10:37 UTC, ds4pae commented on src/main/java/PlayBaseballGame.java
> +public class PlayBaseballGame {
`Strike`, `Ball` 객체 추가했습니다
`checkStrike` `checkBall` 메소드를 이용해  `PlayBaseballGame` 내 `checkStrikeBall` 메소드 로직 변경했습니다!

2023-07-05 09:04 UTC, DongGeon0908 requested changes
요구사항 맞춰서 수정이용

2023-07-05 09:04 UTC, DongGeon0908 commented on src/main/java/Ball.java
> +    private int ball;
final 키워드에 대해 알려주세요

2023-07-05 09:04 UTC, DongGeon0908 commented on src/main/java/PlayBaseballGame.java
> +        System.out.println("RandomValue : " + randomValue);
output 분리

2023-07-05 09:04 UTC, DongGeon0908 commented on src/main/java/PlayBaseballGame.java
> +        for (int count = 0; count < 3; count++) {
사용자가 3번만 입력 가능한거에요?

2023-07-07 04:34 UTC, ds4pae commented on src/main/java/PlayBaseballGame.java
> +        for (int count = 0; count < 3; count++) {
아닙니다!
- for문은 3회 체크하기 위한 코드입니다
```
while(true) {
            String inputValue = GetInputValue.getInputValue();
```
이 코드에서 입력을 받습니다.

- 입력은 `3 strike`가 나올 때 까지 계속 반복하며, `BaseballGame()` 에서 `strike`가 `3`일 시, `System.out(0);`으로 while문을 벗어납니다.

2023-07-07 04:36 UTC, ds4pae commented on src/main/java/PlayBaseballGame.java
> +        System.out.println("RandomValue : " + randomValue);
코드를 Test해볼 때, RandomValue 값을 보고 이상 없는지 체크하기 위해 넣은 코드입니다!
주석을 달아 추가 설명하도록 수정하겠습니다.

2023-07-07 04:42 UTC, ds4pae commented on src/main/java/Ball.java
> +    private int ball;
`final`키워드는 쉽게 말해 ReadOnly의 느낌으로 해석했습니다.
`final`키워드 삽입 시, 종속이 불가능하며 값의 수정이 불가능합니다.

```java
  private final int ball;

  public Ball(int ball) {
    this.ball = ball;
  }
``` 
이런 식으로 `ball`값을 전해주었을 때 제한 사항이 없는지 확인하고 적용해보겠습니다.

2023-07-15 17:54 UTC, DongGeon0908 reviewed
nextstep
- interface
- abstract class

2023-07-15 17:54 UTC, DongGeon0908 commented on src/main/java/PlayBaseballGame.java
> +public class PlayBaseballGame {
strike와 ball은 모두 같은 성질을 지닌 메서드가 있는 것 같은데요
이런 것들 interface를 통한 구현으로 진행하는 건 어떨까요?

2023-07-16 10:55 UTC, ds4pae commented
**`Strike`와 `Ball `의 `BaseBallResult interface`구현**
- `checkBall,checkStrike` -> `checkInput` 
- `getBall,getStrike` -> `getResult`

2023-07-29 06:15 UTC, DongGeon0908 reviewed
여기서 일단 종료하죠.
네이밍이 좀 이상한 것들이 몇개 있네요.

2023-07-29 06:15 UTC, merged